[theme]
primaryColor = "#1976d2"
backgroundColor = "#f5f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#1d1d1f"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false